### ISSUE TITLE
Improve performance of JSONReader and CBORReader

### ISSUE THREAD

**Issue by dustmop** [qri-io/dataset#108]
Recently added benchmarks (88a59db236ea1) revealed that both JSON and CBOR readers have less than ideal performance, compared to writing and compared to reading CSV.

    BenchmarkCBORWriterArrays-2    	    3000	    423851 ns/op
    BenchmarkCBORWriterObjects-2   	    2000	    572609 ns/op
    BenchmarkCBORReader-2          	     300	   5024830 ns/op
    BenchmarkCSVWriterArrays-2     	    1000	   1448891 ns/op
    BenchmarkCSVWriterObjects-2    	    1000	   1457973 ns/op
    BenchmarkCSVReader-2           	    1000	   1454932 ns/op
    BenchmarkJSONWriterArrays-2    	    1000	   1423156 ns/op
    BenchmarkJSONWriterObjects-2   	    1000	   1620801 ns/op
    BenchmarkJSONReader-2          	     300	   5286851 ns/op

A possible first step is to replace string allocations with slices.

**Comment by b5** [comment]
now that #160 is merged, our CBOR reads are much faster :)
```
BenchmarkCBORWriterArrays-2    	    3000	    431290 ns/op
BenchmarkCBORWriterObjects-2   	    2000	    698920 ns/op
BenchmarkCBORReader-2          	    1000	   1764549 ns/op
BenchmarkCSVWriterArrays-2     	    1000	   1548509 ns/op
BenchmarkCSVWriterObjects-2    	    1000	   1458219 ns/op
BenchmarkCSVReader-2           	    1000	   2008097 ns/op
BenchmarkJSONWriterArrays-2    	    1000	   1556416 ns/op
BenchmarkJSONWriterObjects-2   	    1000	   1562488 ns/op
BenchmarkJSONReader-2          	     500	   2984057 ns/op
```

While things can always be better, this is a great start, and warrants closing this issue in favour of a new one with an eye toward more general performance pickups
