### ISSUE TITLE
expand unit test for vals/ConvertDecoded

### ISSUE THREAD

**Issue by b5** [qri-io/dataset#207]
We expanded our `vals.ConvertDecoded` function a little while ago to support additional types, but forgot to add tests to cover these types. Here's the function itself:

https://github.com/qri-io/dataset/blob/5298f1c141653d67efe893b2164bb773bd4ab5b0/vals/coding.go#L9-L69

ConvertDecoded is a utility function that turns standard go types into a _Value_ that Qri uses for further processing. It's a very low level function that should be fully tested. We use a _table test_ to run a number of different inputs checking the results.

https://github.com/qri-io/dataset/blob/5298f1c141653d67efe893b2164bb773bd4ab5b0/vals/coding_test.go#L16-L54

The `cases` slice in our table test is missing the following input types ([codecov shows this clearly](https://codecov.io/gh/qri-io/dataset/src/master/vals/coding.go))

* uint8
* uint16
* uint64
* int32
* int64
* map[interface]interface{}

We should add inputs of each of those types and an expect of the corresponding Value type. For example: `ConvertDecoded` we can see `uint8` will return an `Integer` type.

### Steps to complete
* Fork the dataset repo
* add test cases to `TestConvertDecoded` in `dataset/vals/coding_test.go` for each of the above types, passing an `in` type from the above list, and an `expect` type of the corresponding return value of `ConvertDecoded`
* run the tests to make sure everything passes
* add a commit with a message that follows our commit guidelines. something like `test(vals): expand tests for ConvertDecoded`
* open a PR!

**Comment by dinet** [comment]
Hi @b5, Can I fix this issue?

**Comment by b5** [comment]
Absolutely! Let us know if you have any questions as you go 😄
