### ISSUE TITLE
detect interprets comma-separated integers as strings

### ISSUE THREAD

**Issue by b5** [qri-io/dataset#24]
`123,456,789` = `string`
bad. fix.

**Comment by Arqu** [comment]
This still exists, the culprit:
https://github.com/qri-io/dataset/blob/master/vals/type.go#L74

It correctly tests for a number as the first bytes are a valid number, however it fails to parse it as a float and thus defaults to `TypeString`.

**Comment by Arqu** [comment]
Based on internal discussion we came to the following conclusion:
- We should avoid type guessing as it is almost exlusively linked to CSV handling
- It would also have to be reflected across the codebase

As such this is "as intended" behavior and all floating point numbers should follow the general style of IEEE decimal floating points. In this case that means a single period (`.`) should be used to denominate the integer from the fractional part. No other digit grouping or separators should be used to ensure consistent behavior. All other cases should default to `TypeString`.
