### ISSUE TITLE
Rename "kind" field to "qri", remove "qri:" prefix on kind

### ISSUE THREAD

**Issue by b5** [qri-io/dataset#45]
You may be wondering what the "kind" field in a qri dataset is. The initial reasons for it's existence came up when doing the initial work on an IPLD adapter for qri that elucidated a requirement we've been ignoring to some extent:

**for any given file created by qri, it must be possible to disambiguate the purpose of that file, using only information stored in the file itself**

The real world example of this is file extensions on "regular" files. If I have a file on my machine that ends in `.csv`, I know the _purpose_ of that file is to hold comma-separated values. The purpose is stored in the file extension.

On the distributed web, we can't really count on that because "filenames" are hashes, and extensions are a kind of metadata. We've been getting around this constraint in qri by checking for `/[hash]/dataset.json`, which declares the purpose of this hash is to be a qri dataset, effectively treating `/dataset.json` as a kind of "file extension", and so far that's worked.

Two problems here:
1. Someone could/can/will write a hash dir that has a file `/[hash]/dataset.json` that isn't qri data.
2. Without access to the file's path (aka, examining the file out of context), we can't tell if it's qri data.

IPLD requires we be able to resolve the purpose of a file out of context, which gave rise to the `kind` value you see all over the place. We need variations on `kind`: `"qri:cm:0"`,`"qri:ds:0"`, etc. because we're writing all sorts of files to that hash directory, and each has a different purpose. The `0` bit gives us a versioning escape hatch for when we may need to change the way any of these kinds works from version to version of qri. Ideally we change this figure as little as possible.

So, that brings me to the rename. I find the name "kind" ambiguous, and am worried that it'll eventually collide with some other need. for the word "kind" in the future.  So let's do two things:

1. Rename `"kind"` to `"qri"`
2. Drop the `qri:` prefix on Kind

The initial reason for this was to provide a way for others to use our spec in new and novel ways, changing "qri:" to some other prefix.  But I'm realizing we can change "kind" have that by having users _not_ spefiy the "qri" keyword, and use some other keyword instead. Also, repeating "qri" as a prefix seems repetitive and silly.

So let's make those two changes, which is going to affect a bunch of code, but unless anyone objects, I'd like to ship this for 0.1.0.

Word.

**Comment by ramfox** [comment]
To be clear, the prefix you are talking about is the "qri" part of "qri:cm:0" or "qri:ds:0"?

Now shortened to "cm:0" or "ds:0"?

**Comment by osterbit** [comment]
yes
