### ISSUE TITLE
Use datasetDiffer to infer default commit titles

### ISSUE THREAD

**Issue by b5** [qri-io/dataset#48]
Currently `commit.Title` is required to pass validation (if it isn't, it should be 😄, and I'd love to make sure we have tests that confirm this). Since datasets may change at a very high frequency, or by the result of some machine-based process, we shouldn't require users to hand-enter a commit message. But, unlike git we're only about datasets, which means we can _infer_ a message by examining what's changed. Thankfully there's a package for that, so let's put it to use:

### Steps to Complete
* [x] Someone at qri opens up the datasetDiffer repo
* [x] open a WIP PR so others can see what you're doing, be sure to follow our developer guidelines for easy merging later.
* [ ] modify dsfs.CreateDataset to:
    * Check for a user supplied dataset (`commit.Title != ""`)
    * If no message is supplied, in the `prepareDataset` func, let's infer a commit message using datasetDiffer's string representation methods
* [ ] update tests to check for these inferences
* [ ] request a review of your PR, then 👯‍♂️

**Comment by osterbit** [comment]
@b5 question on initial commits:
- currently datasetDiffer will err if one of the datasets is nil
- would it make more sense to 
   1. update to allow the first dataset to be nil and either
      a. report back that there was a diff on structure and on data
      b. treat as a special case and return "initial commit"
   2. or keep diffDataset as-is and manage the case within dsfs.PrepareDataset (if prev is nil, then we don't call diffDataset or something)

**Comment by osterbit** [comment]
*also I guess it's worth considering more broadly/beyond initial commits
(do we allow either dataset to be nil or should that be an error)

**Comment by b5** [comment]
yeah I'd generally allocate a special "identity" dataset as prev & pass that to datasetDiffer in all situations where "prev" doesn't exist. initial commits are the act of going from nothing (empty dataset). Identity dataset would be a dataset with all _required_ structs allocated but empty. No paths, no values. something like: 
```go
var IdentityDataset = &dataset.Dataset{
  Commit: &dataset.Commit{},
  Structure: &dataset.Structure{},
  // ... etc for any values that need to exist to diff a dataset
}
```
This identity dataset should _not_ pass validation checks, but should result in a diff that shows only "additions" (which I'm pretty sure are currently just "changes")
