### ISSUE TITLE
After using Assign() function, we can be left with a path that doesn't represent the struct accurately

### ISSUE THREAD

**Issue by ramfox** [qri-io/dataset#85]
In qri/core, we use the dataset.Assign function to assign changes to a dataset, compressing the previous dataset and the change dataset into one. However, the assign function also assigns the paths, which will not be accurate if the assigned datasets are different in anyway. This ends up giving us bugs in datasetDiffer, which will assume that two metadata files or structure files are the same if their paths are the same.

options:
1) assign does not mess with paths: all datasets/metadata/structures etc. that have been assigned will not take the paths of the datasets/metadata/structures etc. that were assigned to it (or is assign smart, and take the path when all fields are the same? And clear the path if anything has changed?)
2) create exported function that allows you to clear the paths of datasets/metadata/structures etc.
that we call after we assign?
3) datasetDiffer should change. (My gut is no, and that really paths should be strictly representing only what they are actually the hash of)

1 seems... better.

My concerns with going with option 1 are:
- sometimes our metadata/dataset structs are literally only paths, and what if that is what we wanted to assign? I guess, you would get the path using, eg, meta.Path() and then create a new metadata using NewMetaRef() and passing it the path? Then you can assign whatever you want to it.
- Trying to think of a case where we would want to keep the path, but wouldn't be able to. Can't think of anything right now. Thoughts?

**Comment by b5** [comment]
I've encountered this in the past, and used the following workaround. Assume `ds` is an allocated, hydrated dataset, and `changes` is a dataset of alterations
```golang
ds.Assign(changes, dataset.NewDatasetRef(ds.Path()))
```
This leverages the fact that `Assign` gives right-argument precedence. `ds.Path()` extracts the original path and re-applies it to the dataset to un-clobber whatever `changes` has to say about the path property. 

This technique can be applied to anything you'd like to see not-changed, by supplying the previous values as an argument following changes.

**Comment by ramfox** [comment]
Okay, cool. 
In this particular case, though, its the meta and structure's path that is getting overwritten, not the dataset path.

Also, if ds.Path() is an empty string, wouldn't it get over ridden anyway?

**Comment by b5** [comment]
time for ugly code:
```golang
ds.Assign(changes, &dataset.Dataset{
  Structure: dataset.NewStructureRef(ds.Structure.Path()),
  Meta: dataset.NewMetaRef(ds.Meta.Path()),
})
```

yes if ds.Path() is empty, it'll get overwritten. Shit.

**Comment by ramfox** [comment]
k, but the meta and structure paths are empty too lol

**Comment by b5** [comment]
lol it's like you want the code to work or something

**Comment by b5** [comment]
can you push up a branch with option 1 so we can have a look? Do all the tests pass?

**Comment by ramfox** [comment]
For now I will just write over the structure and meta paths, to have them be what they were before the clobbering.

But can I posit that maybe we don't ever want to keep the path after an assign? Unless we are guaranteed the original dataset and this new assigned dataset have the same contents?

Maybe I'm coming at this the wrong way, but it feels to me that if we are using the path as a guarantee that two structs are the same, then we should be guaranteeing they are the same

**Comment by b5** [comment]
completely agreed. Any call to assign should clobber the path. I'm sold, and now impatiently awaiting code that proves you right

**Comment by ramfox** [comment]
LOLLL

**Comment by ramfox** [comment]
Will work on it now. Never got to it because it seemed like to big a shift without discussion

**Comment by ramfox** [comment]
Wait! to be clear: all calls to assign will make it so that the path is empty after the call.

**Comment by ramfox** [comment]
Wait, literally the first thing I just looked at used assign to assign one path to another dataset

**Comment by b5** [comment]
Ok, time for a new Method on all components of dataset that have `Assign`:

```golang
// SetPath sets the internal path property of a dataset
// Use with caution. most callers should never need to call SetPath
func (ds *Dataset) SetPath(path string) {
  ds.path = datastore.NewKey(path)
}
```
Let's combine this with a change to `Assign` that makes it always set the path to empty string.

We'll pull this out in subsequent refactors, but at least now we'll be able to see all places in the codebase where we need path manipulation.

**Comment by ramfox** [comment]
Dope! will do.

**Comment by ramfox** [comment]
OKAY SO

After messing with Assign, it seems that if we don't assign the path, we can run into cases where we completely smash a dataset/structure/metadata, if the struct is a reference.

SO

We will leave all the Assign functions as is, but add still add the new function `SetPath` for those edge cases where we NEED the path to be specific
